---
apiVersion: networking.gke.io/v1
kind: GCPGatewayPolicy
metadata:
  name: tls13-ssl-policy
  namespace: cilium
spec:
  default:
    sslPolicy: tls13-policy
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: mdch-lab
