- op: add
  path: /spec/values
  value:
    gke:
      enabled: true
    ipam:
      mode: kubernetes
    cni:
      binPath: /home/kubernetes/bin
    nodeinit:
      enabled: true
      reconfigureKubelet: true
      removeCbrBridge: true
      removeNodeTaints: true
    ipv4NativeRoutingCIDR: 10.50.32.0/20
    agentNotReadyTaintKey: "ignore-taint.cluster-autoscaler.kubernetes.io/cilium-not-ready"
    operator:
      podDisruptionBudget:
        enabled: true
